# Generated by Django 5.0.6 on 2024-06-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='game',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='game_photos/'),
        ),
    ]
