# Generated by Django 5.0.6 on 2024-06-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url_editor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
