# Generated by Django 5.0.6 on 2024-06-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_url_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='game_photos/'),
        ),
    ]
