# Generated by Django 5.0.6 on 2024-06-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url_editor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
