# Generated by Django 5.0.6 on 2024-06-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_drink_photo_path_drink_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drink',
            name='is_soft',
            field=models.BooleanField(default=0),
        ),
    ]
