# Generated by Django 5.0.6 on 2024-06-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_drink_id_alter_drink_is_soft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='drink_photos/'),
        ),
    ]
